export type PermissionScope = "tenant" | "assigned" | "platform";

export type Permission = `${string}:${string}:${PermissionScope}` | `platform:${string}`;

export const PERMISSIONS = {
  PLATFORM_TENANT_CREATE: "platform:tenant:create",
  PLATFORM_TENANT_READ: "platform:tenant:read",
  PLATFORM_TENANT_UPDATE: "platform:tenant:update",
  PLATFORM_IMPERSONATE: "platform:impersonate:platform",

  TENANT_READ: "tenant:read:tenant",
  TENANT_UPDATE: "tenant:update:tenant",

  PROPERTY_CREATE: "property:create:tenant",
  PROPERTY_READ_TENANT: "property:read:tenant",
  PROPERTY_READ_ASSIGNED: "property:read:assigned",
  PROPERTY_UPDATE_TENANT: "property:update:tenant",
  PROPERTY_UPDATE_ASSIGNED: "property:update:assigned",
  PROPERTY_DELETE_TENANT: "property:delete:tenant",

  MEMBER_INVITE: "member:invite:tenant",
  MEMBER_READ: "member:read:tenant",
  MEMBER_UPDATE: "member:update:tenant",
  MEMBER_REVOKE: "member:revoke:tenant",

  COMMERCE_READ: "commerce:read:tenant",
  COMMERCE_UPDATE: "commerce:update:tenant",

  KEY_READ: "key:read:tenant",
  KEY_CREATE: "key:create:tenant",
  KEY_REVOKE: "key:revoke:tenant",
  KEY_UPDATE: "key:update:tenant",

  AVAILABILITY_READ_TENANT: "availability:read:tenant",
  AVAILABILITY_READ_ASSIGNED: "availability:read:assigned",
  AVAILABILITY_UPDATE_TENANT: "availability:update:tenant",
  PRICING_READ_TENANT: "pricing:read:tenant",
  PRICING_READ_ASSIGNED: "pricing:read:assigned",
  PRICING_UPDATE_TENANT: "pricing:update:tenant",
  HOLD_CREATE_TENANT: "hold:create:tenant",
  HOLD_READ: "hold:read:tenant",
  QUOTE_CREATE_TENANT: "quote:create:tenant",
  BOOKING_READ_TENANT: "booking:read:tenant",
  BOOKING_READ_ASSIGNED: "booking:read:assigned",
  BOOKING_CREATE_TENANT: "booking:create:tenant",
  BOOKING_UPDATE_TENANT: "booking:update:tenant",
  BOOKING_CANCEL_TENANT: "booking:cancel:tenant",

  /** Tenant-wide Guest CRM read (Admin / Super Admin Open). */
  GUEST_READ_TENANT: "guest:read:tenant",
  /** Manager: Guest identity only when authorized Property activity exists. */
  GUEST_READ_ASSIGNED: "guest:read:assigned",
  GUEST_CREATE_TENANT: "guest:create:tenant",
  GUEST_UPDATE_TENANT: "guest:update:tenant",

  /** Manage channel connections and non-elevated feed semantic modes. */
  CHANNELS_CONNECTION_MANAGE: "channels:connection:manage:tenant",
  /** Elevated: declare reservation_feed semantic mode (not Booking import enablement). */
  CHANNELS_CONNECTION_DECLARE_RESERVATION_FEED:
    "channels:connection:declare_reservation_feed:tenant",
} as const satisfies Record<string, Permission>;

export type TenantRole = "admin" | "manager";

export const ROLE_PERMISSIONS: Record<TenantRole, readonly Permission[]> = {
  admin: [
    PERMISSIONS.TENANT_READ,
    PERMISSIONS.TENANT_UPDATE,
    PERMISSIONS.PROPERTY_CREATE,
    PERMISSIONS.PROPERTY_READ_TENANT,
    PERMISSIONS.PROPERTY_UPDATE_TENANT,
    PERMISSIONS.PROPERTY_DELETE_TENANT,
    PERMISSIONS.MEMBER_INVITE,
    PERMISSIONS.MEMBER_READ,
    PERMISSIONS.MEMBER_UPDATE,
    PERMISSIONS.MEMBER_REVOKE,
    PERMISSIONS.COMMERCE_READ,
    PERMISSIONS.COMMERCE_UPDATE,
    PERMISSIONS.KEY_READ,
    PERMISSIONS.KEY_CREATE,
    PERMISSIONS.KEY_REVOKE,
    PERMISSIONS.KEY_UPDATE,
    PERMISSIONS.AVAILABILITY_READ_TENANT,
    PERMISSIONS.AVAILABILITY_UPDATE_TENANT,
    PERMISSIONS.PRICING_READ_TENANT,
    PERMISSIONS.PRICING_UPDATE_TENANT,
    PERMISSIONS.HOLD_CREATE_TENANT,
    PERMISSIONS.HOLD_READ,
    PERMISSIONS.QUOTE_CREATE_TENANT,
    PERMISSIONS.BOOKING_READ_TENANT,
    PERMISSIONS.BOOKING_CREATE_TENANT,
    PERMISSIONS.BOOKING_UPDATE_TENANT,
    PERMISSIONS.BOOKING_CANCEL_TENANT,
    PERMISSIONS.GUEST_READ_TENANT,
    PERMISSIONS.GUEST_CREATE_TENANT,
    PERMISSIONS.GUEST_UPDATE_TENANT,
    PERMISSIONS.CHANNELS_CONNECTION_MANAGE,
    PERMISSIONS.CHANNELS_CONNECTION_DECLARE_RESERVATION_FEED,
  ],
  manager: [
    PERMISSIONS.PROPERTY_READ_ASSIGNED,
    PERMISSIONS.PROPERTY_UPDATE_ASSIGNED,
    PERMISSIONS.AVAILABILITY_READ_ASSIGNED,
    PERMISSIONS.BOOKING_READ_ASSIGNED,
    PERMISSIONS.GUEST_READ_ASSIGNED,
  ],
};

export const SUPER_ADMIN_PERMISSIONS: readonly Permission[] = [
  PERMISSIONS.PLATFORM_TENANT_CREATE,
  PERMISSIONS.PLATFORM_TENANT_READ,
  PERMISSIONS.PLATFORM_TENANT_UPDATE,
  PERMISSIONS.PLATFORM_IMPERSONATE,
  PERMISSIONS.TENANT_READ,
  PERMISSIONS.TENANT_UPDATE,
  PERMISSIONS.PROPERTY_CREATE,
  PERMISSIONS.PROPERTY_READ_TENANT,
  PERMISSIONS.PROPERTY_UPDATE_TENANT,
  PERMISSIONS.PROPERTY_DELETE_TENANT,
  PERMISSIONS.MEMBER_INVITE,
  PERMISSIONS.MEMBER_READ,
  PERMISSIONS.MEMBER_UPDATE,
  PERMISSIONS.MEMBER_REVOKE,
  PERMISSIONS.COMMERCE_READ,
  PERMISSIONS.COMMERCE_UPDATE,
  PERMISSIONS.KEY_READ,
  PERMISSIONS.KEY_CREATE,
  PERMISSIONS.KEY_REVOKE,
  PERMISSIONS.KEY_UPDATE,
  PERMISSIONS.AVAILABILITY_READ_TENANT,
  PERMISSIONS.AVAILABILITY_UPDATE_TENANT,
  PERMISSIONS.PRICING_READ_TENANT,
  PERMISSIONS.PRICING_UPDATE_TENANT,
  PERMISSIONS.HOLD_CREATE_TENANT,
  PERMISSIONS.HOLD_READ,
  PERMISSIONS.QUOTE_CREATE_TENANT,
  PERMISSIONS.BOOKING_READ_TENANT,
  PERMISSIONS.BOOKING_CREATE_TENANT,
  PERMISSIONS.BOOKING_UPDATE_TENANT,
  PERMISSIONS.BOOKING_CANCEL_TENANT,
  PERMISSIONS.GUEST_READ_TENANT,
  PERMISSIONS.GUEST_CREATE_TENANT,
  PERMISSIONS.GUEST_UPDATE_TENANT,
  PERMISSIONS.CHANNELS_CONNECTION_MANAGE,
  PERMISSIONS.CHANNELS_CONNECTION_DECLARE_RESERVATION_FEED,
];
