export const LOGGING_PING_JOB_TYPE = "logging_ping";
export const EXPIRE_HOLDS_JOB_TYPE = "expire_holds";
export const PROCESS_CHANNEL_INBOX_JOB_TYPE = "process_channel_inbox";
export const POLL_CHANNEL_CONNECTION_JOB_TYPE = "poll_channel_connection";
export const RECONCILE_ICAL_IMPORTED_INVENTORY_JOB_TYPE =
  "reconcile_ical_imported_inventory";
export const SWEEP_PENDING_ICAL_INVENTORY_RECONCILE_JOB_TYPE =
  "sweep_pending_ical_inventory_reconcile";

export const JOB_TYPES = {
  LOGGING_PING: LOGGING_PING_JOB_TYPE,
  EXPIRE_HOLDS: EXPIRE_HOLDS_JOB_TYPE,
  PROCESS_CHANNEL_INBOX: PROCESS_CHANNEL_INBOX_JOB_TYPE,
  POLL_CHANNEL_CONNECTION: POLL_CHANNEL_CONNECTION_JOB_TYPE,
  RECONCILE_ICAL_IMPORTED_INVENTORY: RECONCILE_ICAL_IMPORTED_INVENTORY_JOB_TYPE,
  SWEEP_PENDING_ICAL_INVENTORY_RECONCILE: SWEEP_PENDING_ICAL_INVENTORY_RECONCILE_JOB_TYPE,
} as const;
