export const LOGGING_PING_JOB_TYPE = "logging_ping";
export const EXPIRE_HOLDS_JOB_TYPE = "expire_holds";
export const PROCESS_CHANNEL_INBOX_JOB_TYPE = "process_channel_inbox";
export const POLL_CHANNEL_CONNECTION_JOB_TYPE = "poll_channel_connection";
export const RECONCILE_ICAL_IMPORTED_INVENTORY_JOB_TYPE =
  "reconcile_ical_imported_inventory";
export const SWEEP_PENDING_ICAL_INVENTORY_RECONCILE_JOB_TYPE =
  "sweep_pending_ical_inventory_reconcile";
export const PUSH_BOOKING_COM_ARI_JOB_TYPE = "push_booking_com_ari";
export const GENERATE_HOUSEKEEPING_TURNOVER_JOB_TYPE =
  "generate_housekeeping_turnover";
export const MESSAGING_AUTOMATION_DISPATCH_JOB_TYPE =
  "messaging.automation.dispatch";
export const MESSAGING_WHATSAPP_SEND_TEMPLATE_JOB_TYPE =
  "messaging.whatsapp.send_template";
export const MESSAGING_WHATSAPP_SEND_SESSION_JOB_TYPE =
  "messaging.whatsapp.send_session";

export const JOB_TYPES = {
  LOGGING_PING: LOGGING_PING_JOB_TYPE,
  EXPIRE_HOLDS: EXPIRE_HOLDS_JOB_TYPE,
  PROCESS_CHANNEL_INBOX: PROCESS_CHANNEL_INBOX_JOB_TYPE,
  POLL_CHANNEL_CONNECTION: POLL_CHANNEL_CONNECTION_JOB_TYPE,
  RECONCILE_ICAL_IMPORTED_INVENTORY: RECONCILE_ICAL_IMPORTED_INVENTORY_JOB_TYPE,
  SWEEP_PENDING_ICAL_INVENTORY_RECONCILE: SWEEP_PENDING_ICAL_INVENTORY_RECONCILE_JOB_TYPE,
  PUSH_BOOKING_COM_ARI: PUSH_BOOKING_COM_ARI_JOB_TYPE,
  GENERATE_HOUSEKEEPING_TURNOVER: GENERATE_HOUSEKEEPING_TURNOVER_JOB_TYPE,
  MESSAGING_AUTOMATION_DISPATCH: MESSAGING_AUTOMATION_DISPATCH_JOB_TYPE,
  MESSAGING_WHATSAPP_SEND_TEMPLATE: MESSAGING_WHATSAPP_SEND_TEMPLATE_JOB_TYPE,
  MESSAGING_WHATSAPP_SEND_SESSION: MESSAGING_WHATSAPP_SEND_SESSION_JOB_TYPE,
} as const;
