/** Curated country list for Get Started — free-text also accepted by the API. */
export const LEAD_COUNTRY_OPTIONS = [
  "Greece",
  "Cyprus",
  "Italy",
  "Spain",
  "Portugal",
  "France",
  "Croatia",
  "United Kingdom",
  "Germany",
  "Netherlands",
  "Belgium",
  "Austria",
  "Switzerland",
  "United States",
  "Canada",
  "Australia",
  "United Arab Emirates",
  "Turkey",
  "Bulgaria",
  "Romania",
  "Poland",
  "Czechia",
  "Hungary",
  "Ireland",
  "Sweden",
  "Norway",
  "Denmark",
  "Finland",
  "Malta",
  "Other",
] as const;
